config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :pages, only: [:index, :home]

  resources :messages, only: [:index, :new, :create]

  resources :journals, only: [:show, :index, :new, :create] do
    resources :entries, only: [:index, :new, :create]
  end

resources :entries do
    resources :milestones, only: [:new, :create]
  end

  resources :milestones, only: [:show] do
    resources :pomodoros, only: [:new, :create]
  end


  resources :pomodoros, only: [:show, :update]
  resources :profiles, only: [:show, :edit, :update]
  resources :entries, only: [:show]



   # resources :profile, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pomodoro.rb
class Pomodoro < ApplicationRecord
  belongs_to :milestone, optional: true
  belongs_to :user, optional: true

  def seconds
    total = 0
      if start.nil? || self.end.nil?
        time_length = 0
      else
        time_length = (self.end - self.start).to_i
      end
      total += time_length
  end

  def time
    seconds = self.seconds
    if seconds >= 60 * 60
      minutes = seconds / 60
      hours = minutes / 60
      minutes = minutes % 60
      seconds = seconds % 60

      "#{hours} h #{minutes} min"
    else seconds >= 60
      minutes = seconds / 60
      seconds = seconds % 60
      "#{minutes} min"
    end
  end
end


# def time
#     seconds = self.seconds
#     if seconds >= 60 * 60
#       minutes = seconds / 60
#       hours = minutes / 60
#       minutes = minutes % 60
#       seconds = seconds % 60

#       "#{hours} h #{minutes} min #{seconds}"
#     elsif seconds >= 60
#       minutes = seconds / 60
#       seconds = seconds % 60
#       "#{minutes} m #{seconds} s"
#     else
#       "#{seconds} s"
#     end
#   end

app/controllers/pomodoros_controller.rb
class PomodorosController < ApplicationController
  def new
    @pomodoro = Pomodoro.new
    @milestone = Milestone.find(params[:milestone_id])
  end

  def create
    @pomodoro = Pomodoro.new
    @pomodoro.milestone = Milestone.find(params[:milestone_id])
    @pomodoro.save!
    # redirect_to pomodoro_path(@pomodoro)
    redirect_to @pomodoro
  end

  def show
    # time_frame = 25
    # @duration = 25.minutes
    @pomodoro = Pomodoro.find(params[:id])

    # @remaining_seconds = (@pomodoro.created_at + @duration - Time.now).to_i

    # mins = @remaining_seconds / 60
    # seconds = @remaining_seconds % 60

    # @remaining = "#{mins}min #{seconds}sec"

    @entry = @pomodoro.milestone.entry
    @journal = @entry.journal
    @milestone = @pomodoro.milestone
  end

  def update
    @pomodoro = Pomodoro.find(params[:id])
    @journal = @pomodoro.milestone.entry.journal

    if params[:pomodoro]
      if params[:pomodoro][:action] == 'start'
        @pomodoro.start = Time.now
        @pomodoro.end = @pomodoro.start + 25.minutes
      elsif params[:pomodoro][:action] == 'done'
      end
    else
      @pomodoro.stars = params["stars"]
      @pomodoro.save!
      redirect_to journal_entries_path(@journal)
    end
    @pomodoro.save!
  end
end

# remove line 39 - hacky way to show 25 min on evaluation page
# line 40 - change back after prezi @pomodoro.end = Time.now

app/views/pomodoros/new.html.erb
<div class="container-main">
<h1>Pomodoros#new</h1>
<p>Find me in app/views/pomodoros/new.html.erb</p>

<%= simple_form_for([@milestone, @pomodoro]) do |f| %>
  <%= f.submit %>
<% end %>
</div>

app/views/pomodoros/show.html.erb
<div class="container-main">
<% content_for :meta_title, "#{@milestone.title} is your focus now" %>
<div class="content2">
<div class="card-journal-book-top">
  <div class="card-journal-book-text">
  <!-- <h4>  Session <%=@milestone.title %> </h4> -->
  </div>
</div>
<!-- <div class="card-pomodoro"> -->
 

<div id="pomodoro">
     <div id="countdown">
        <span id="minutes">25</span>
        <span>:</span>
        <span id="seconds">00</span>
      </div>
  <div id="options">
    <div id="session">
      <i id="decrSession" class="fas fa-minus-square"></i>
      <span class="option-title"></span>
      <!-- <input id="sessionInput" type="number" value="25" max="25" min="25"> -->
      <i id="incrSession" class="fas fa-plus-square"></i>
      <span class="option-title" ></span>
    </div>
  </div>

  <div id="clock">
    <div id="timer">

    <div id="controls" class="reset">
      <div class="start-stop">
      <div id="start">
          <%= simple_form_for @pomodoro, remote: true do |f| %>
            <%= f.input :action, as: :hidden, input_html: { value: 'start' } %>
            <%= button_tag :class => 'btn-tag' do %>
            <p>Start</p>
            <% end %>
          <% end %>
      </div>

      <div id="done">
        <%= simple_form_for @pomodoro, remote: true do |f| %>
          <%= f.input :action, as: :hidden, input_html: { value: 'done' } %>
            <%= button_tag :class => 'btn-tag' do %>
              <p>Done</p>
          <% end %>
        <% end %>
      </div>
    </div>
      <div id="back">
        <%= link_to milestone_path(@milestone, pomodoro_id: @pomodoro.id) do %>
          <p>Evaluate Your Session</p>
          <div class="back-fade-in">
          <!-- <img class="vert-move fade-in" src="https://res.cloudinary.com/doem0zjpf/image/upload/v1563012445/zxc_vvjt4c.png" alt=""> -->
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div id="note">
  </div>
    </div>
  </div>
<audio loop autostart="0" src="https://joeweaver.me/codepenassets/freecodecamp/challenges/build-a-pomodoro-clock/forest.mp3"></audio>



</div>


<script>
const time = 25;
window.time = time;
const up = document.getElementById("incrSession");
up.addEventListener("click", (event)=> {
  if (window.time <= 59) {
    window.time += 1;
    document.getElementById("minutes").innerText = window.time;
    document.getElementById("sessionInput").value = window.time;
  }
});
const down = document.getElementById("decrSession");
down.addEventListener("click", (event)=> {
  window.time -= 1;
  document.getElementById("minutes").innerText = window.time;
  document.getElementById("sessionInput").value = window.time;
});
const start = document.querySelector("#start");
// start.addEventListener("click", (event)=> {
//   const myAudio = document.querySelector("audio");
  // myAudio.play();
  // myAudio.pause();
// });
</script>

app/views/pomodoros/update.js.erb
$(() => {
  const $audio = $('audio'); // from https://tide.moreless.io/en/
  const $theme = $('.theme');
  const $title = $('#title');
  const $controls = $('#controls');
  const $options = $('#options');
  const $minutes = $('#minutes');
  const $seconds = $('#seconds');
  const $start = $('#start');
  const $pause = $('#pause');
  const $done = $('#done');
  const $reset = $('#reset');
  const $back = $('#back');
  const $incrSession = $("#incrSession");
  const $sessionInput = $('#sessionInput');
  const $decrSession = $("#decrSession");
  // $incrBreak = $("#incrBreak"),
  // $breakInput = $("#breakInput"),
  // $decrBreak = $("#decrBreak"),
  // breakLength = 5 * 60,
  // breakMax = 5,
  // breakMin = 5,
  let sessionLength = window.time * 60;
  const sessionMax = 60;
  const sessionMin = 1;
  let sessionNum = 0;
  let countdown;
  let countType;
  let remainingTime = sessionLength;

  init();

  function init() {
    $audio.prop("volume", 0);
    console.log($incrSession);
    $incrSession.click(() => incrSession());
    $decrSession.click(() => decrSession());
    // $incrBreak.click(() => incrBreak());
    // $decrBreak.click(() => decrBreak());
    // $sessionInput.on("change", e => updateSession(e.target.value));
    // $breakInput.on("change", e => updateBreak(e.target.value));
    //$start.click(() => {
      // if (countType === "break"){
      //   startBreak();
      // }
      // else {
    if ($controls.hasClass("reset")) {
      startSession();
      // }
    } else {
      done();
    }
    // $pause.click(() => pause());
    // $reset.click(() => reset());
    // $theme.click(e => audioSelect(e));
  }
  function startSession() {
    sessionNum++;
    countType = 'session';
    // $options.slideUp(143);
    $controls.removeClass().addClass('started');
    $title.fadeOut(43, function () {
    $(this).html(`Session`).fadeIn();    });
    // $audio.animate({ volume: 1 }, 1000);
    start(remainingTime || sessionLength);
  }
  // function startBreak(){
  //   countType = "break";
  //   $title.fadeOut(43, function(){
  //     $(this).html("Break " + sessionNum).fadeIn();
  //   });
  //   $audio.animate({volume: 0}, 5000);
  //   start(remainingTime || breakLength);
  // }
  function start(timeLeft) {
    clearInterval(countdown);
    countdown = setInterval(() => {
      window.countdownFromStart = countdown;
      timeLeft--;
      remainingTime = timeLeft;
      const minLeft = Math.floor(timeLeft / 60);
      const secLeft = timeLeft - minLeft * 60;
      updateMinutes(minLeft);
      updateSeconds(secLeft < 10 ? `0${secLeft}` : secLeft);
      if (timeLeft < 1) {
        if (countType === 'session') {
          // startBreak(breakLength);
          // if sessiong finished by time Display the button Confirm your session

          $audio.animate({ volume: 1 }, 3000);
          $audio[0].play();
          done();
        } else {
          startSession();
        }
      }
    }, 1000);
  }
  function done() {
    sessionNum--;
    // $audio.animate({volume: 0}, 1000);
    clearInterval(window.countdownFromStart);
    // $options.slideDown(143);
    $controls.removeClass().addClass('done');
    $title.fadeOut(43, function () {
      $(this).html('Done').fadeIn();
    });
  }
  // function pause(){
  //   sessionNum--;
  //   $audio.animate({volume: 0}, 1000);
  //   clearInterval(countdown);
  //   $options.slideDown(143);
  //   $controls.removeClass().addClass("paused");
  //   $title.fadeOut(43, function(){
  //     $(this).html("Paused").fadeIn();
  //   });
  // }
  // function reset(){
  //   clearInterval(countdown);
  //   updateMinutes(sessionLength / 60);
  //   updateSeconds("00");
  //   countType = undefined;
  //   $controls.removeClass().addClass("reset");
  //   $title.html("Ready?");
  //   remainingTime = sessionLength;
  // }

  function incrSession(){
    let num = Number($sessionInput.val());
    num = num + (num === sessionMax ? 0 : 1);
    sessionLength = num * 60;
    updateSession(num);
    updateMinutes(num);
    updateSeconds("00");
    reset();
  }
  function decrSession(){
    let num = Number($sessionInput.val());
    num = num - (num === sessionMin ? 0 : 1);
    sessionLength = num * 60;
    updateSession(num);
    updateMinutes(num);
    updateSeconds("00");
    reset();
  }
  // function incrBreak(){
  //   let num = Number($breakInput.val());
  //   num = num + (num === breakMax ? 0 : 1);
  //   breakLength = num * 60;
  //   updateBreak(num);
  //   reset();
  // }
  // function decrBreak(){
  //   let num = Number($breakInput.val());
  //   num = num - (num === breakMin ? 0 : 1);
  //   breakLength = num * 60;
  //   updateBreak(num);
  //   reset();
  // }
  function updateMinutes(num) {
    $minutes.text(num);
  }
  function updateSeconds(num) {
    $seconds.text(num);
  }
  function updateSession(num) {
    num = num < sessionMin ? sessionMin : num > sessionMax ? sessionMax : num;
    $sessionInput.val(num).blur();
    updateMinutes(num);
    updateSeconds('00');
    sessionLength = num * 60;
    reset();
  }
  // function updateBreak(num) {
  //   $breakInput.val(num < breakMin ? breakMin : num > breakMax ? breakMax : num).blur();
  //   breakLength = num * 60;
  //   reset();
  // }
});