config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :pages, only: [:index, :home]

  resources :messages, only: [:index, :new, :create]

  resources :journals, only: [:show, :index, :new, :create] do
    resources :entries, only: [:index, :new, :create]
  end

resources :entries do
    resources :milestones, only: [:new, :create]
  end

  resources :milestones, only: [:show] do
    resources :pomodoros, only: [:new, :create]
  end


  resources :pomodoros, only: [:show, :update]
  resources :profiles, only: [:show, :edit, :update]
  resources :entries, only: [:show]



   # resources :profile, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
 

   <div class="banner-mainpage" style="background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('https://res.cloudinary.com/doem0zjpf/image/upload/v1574145865/photo-1483721310020-03333e577078_e3wemd.jpg'); background-position:center; background-size:cover;"> 
  <div class="banner-textfield">
  <h1>Beat Procastination</h1>
  <p>Let's get started! Think of a goal you want to work on.</p>
  <div class="button-center">
    <%= link_to "START", new_journal_path, :class => "button-main", :id => "btn-start" %>
    </div>
  </div>
</div> 
<div class="container-main">
<div class="card-instruction-wrapper">
<div class="card-instruction"> 
  <div>
  <h2>1.</h2>
  <p>Being productive can be a daunting task. Find clarity with Conquered Time and start your journey of self-improvement.</p>
  </div>
</div>

<div class="card-instruction"> 
  <div>
  <h2>2.</h2>
  <p>Creating smaller, more manageable milestones builds a map to accomplishing our large goals.</p>
  </div>
</div>

<div class="card-instruction"> 
  <div>
  <h2>3.</h2>
  <p>Start a focus timer on your milestones to avoid distractions and work with complete devotion. It's all about quality over quantity!</p>
  </div>
</div>
</div>
</div>

app/views/pages/index.html.erb
<div class="container-main">
<% content_for :meta_title, "The Leaderboard of Conquered Time" %>
  <div class="card-scoreboard">
    <div class="the-leaderboard">
      <h2>Leaderboard</h2>

    </div>
    <div class="first-place-group">
      <img src="<%= @users.first.avatar %>" alt="Avatar" class="avatar">
      <p class="first-place"><%= @users.first.username %></p>
      <p><%= @users.first.time %></p>
    </div>

    <div class="second-place-group">
      <img src="<%= @users.second.avatar %>" alt="Avatar" class="avatar">
      <p class="second-place"><%= @users.second.username %></p>
      <p><%= @users.second.time %></p>
    </div>

    <div class="third-place-group">
      <img src="<%= @users.third.avatar %>" alt="Avatar" class="avatar">
      <p class="third-place"><%= @users.third.username %></p>
      <p><%= @users.third.time %></p>
    </div>

    <% @not_podium.each do |user| %>
      <% if user.avatar == nil %>
        <% then %>
          <div class="peasants-group">
            <img src="https://res.cloudinary.com/doem0zjpf/image/upload/v1562650336/maskCopy2_3x_vreuag.png" alt="Avatar" class="avatar">
            <p><%= user.username %></p>
            <p><%= user.time %></p>
          </div>
        <% else %>
          <div class="peasants-group3">
            <img src="<%= user.avatar %>" alt="Avatar" class="avatar">
            <p><%= user.username %></p>
            <p><%= user.time %></p>
          </div>
        <% end %>
      <% end %>
    </div>
</div>